//! UnimatrixServer core: state holder and ServerHandler implementation.

use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{Implementation, ServerInfo};
use unimatrix_core::{StoreAdapter, VectorAdapter};
use unimatrix_core::async_wrappers::{AsyncEntryStore, AsyncVectorStore};

use crate::audit::AuditLog;
use crate::embed_handle::EmbedServiceHandle;
use crate::error::ServerError;
use crate::identity::{self, ResolvedIdentity};
use crate::registry::AgentRegistry;

/// Server name reported in MCP initialize handshake.
const SERVER_NAME: &str = "unimatrix";

/// Behavioral instructions for AI agents.
const SERVER_INSTRUCTIONS: &str = "Unimatrix is this project's knowledge engine. Before starting implementation, architecture, or design tasks, search for relevant patterns and conventions using the context tools. Apply what you find. After discovering reusable patterns or making architectural decisions, store them for future reference. Do not store workflow state or process steps.";

/// The central MCP server holding all shared state.
///
/// All fields are Arc-wrapped so Clone is cheap (required by rmcp).
#[derive(Clone)]
pub struct UnimatrixServer {
    /// Async entry store for knowledge operations (used in vnc-002).
    #[allow(dead_code)]
    pub(crate) entry_store: Arc<AsyncEntryStore<StoreAdapter>>,
    /// Async vector store for similarity search (used in vnc-002).
    #[allow(dead_code)]
    pub(crate) vector_store: Arc<AsyncVectorStore<VectorAdapter>>,
    /// Lazy-loading embedding service (used in vnc-002).
    #[allow(dead_code)]
    pub(crate) embed_service: Arc<EmbedServiceHandle>,
    /// Agent registry for identity and capabilities.
    pub(crate) registry: Arc<AgentRegistry>,
    /// Audit log for request tracking.
    pub(crate) audit: Arc<AuditLog>,
    /// Tool router generated by the tool_router macro.
    tool_router: ToolRouter<Self>,
    /// Cached server info for MCP handshake.
    server_info: ServerInfo,
}

impl UnimatrixServer {
    /// Create a new server with all subsystems.
    pub fn new(
        entry_store: Arc<AsyncEntryStore<StoreAdapter>>,
        vector_store: Arc<AsyncVectorStore<VectorAdapter>>,
        embed_service: Arc<EmbedServiceHandle>,
        registry: Arc<AgentRegistry>,
        audit: Arc<AuditLog>,
    ) -> Self {
        let server_info = ServerInfo {
            server_info: Implementation {
                name: SERVER_NAME.to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
                ..Default::default()
            },
            instructions: Some(SERVER_INSTRUCTIONS.to_string()),
            ..Default::default()
        };

        UnimatrixServer {
            entry_store,
            vector_store,
            embed_service,
            registry,
            audit,
            tool_router: Self::tool_router(),
            server_info,
        }
    }

    /// Resolve an agent identity from tool parameters.
    ///
    /// Convenience method combining extraction and resolution.
    pub fn resolve_agent(
        &self,
        agent_id: &Option<String>,
    ) -> Result<ResolvedIdentity, ServerError> {
        let extracted = identity::extract_agent_id(agent_id);
        identity::resolve_identity(&self.registry, &extracted)
    }
}

#[rmcp::tool_handler]
impl rmcp::ServerHandler for UnimatrixServer {
    fn get_info(&self) -> ServerInfo {
        self.server_info.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use unimatrix_store::Store;

    fn make_server() -> UnimatrixServer {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("test.redb");
        let store = Arc::new(Store::open(&path).unwrap());
        std::mem::forget(dir);

        let store_adapter = StoreAdapter::new(Arc::clone(&store));
        let entry_store = Arc::new(AsyncEntryStore::new(Arc::new(store_adapter)));

        // Use a minimal VectorIndex
        let vector_config = unimatrix_core::VectorConfig::default();
        let vector_index = Arc::new(
            unimatrix_core::VectorIndex::new(Arc::clone(&store), vector_config).unwrap(),
        );
        let vector_adapter = VectorAdapter::new(vector_index);
        let vector_store = Arc::new(AsyncVectorStore::new(Arc::new(vector_adapter)));

        let embed_service = EmbedServiceHandle::new();

        let registry = Arc::new(AgentRegistry::new(Arc::clone(&store)).unwrap());
        registry.bootstrap_defaults().unwrap();

        let audit = Arc::new(AuditLog::new(Arc::clone(&store)));

        UnimatrixServer::new(entry_store, vector_store, embed_service, registry, audit)
    }

    #[test]
    fn test_get_info_name() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert_eq!(info.server_info.name, "unimatrix");
    }

    #[test]
    fn test_get_info_version_nonempty() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert!(!info.server_info.version.is_empty());
    }

    #[test]
    fn test_get_info_instructions() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert!(info.instructions.is_some());
        let instructions = info.instructions.unwrap();
        assert!(instructions.contains("knowledge engine"));
        assert!(instructions.contains("search for relevant patterns"));
    }

    #[test]
    fn test_server_is_clone() {
        let server = make_server();
        let _clone = server.clone();
    }

    #[test]
    fn test_resolve_agent_with_id() {
        let server = make_server();
        let identity = server
            .resolve_agent(&Some("human".to_string()))
            .unwrap();
        assert_eq!(identity.agent_id, "human");
        assert_eq!(identity.trust_level, crate::registry::TrustLevel::Privileged);
    }

    #[test]
    fn test_resolve_agent_without_id() {
        let server = make_server();
        let identity = server.resolve_agent(&None).unwrap();
        assert_eq!(identity.agent_id, "anonymous");
    }
}
