//! UnimatrixServer core: state holder and ServerHandler implementation.

use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{Implementation, ServerInfo};
use unimatrix_core::{
    CoreError, EntryRecord, NewEntry, StoreAdapter, Store, VectorAdapter,
};
use unimatrix_core::async_wrappers::{AsyncEntryStore, AsyncVectorStore};
use unimatrix_store::{
    ENTRIES, TOPIC_INDEX, CATEGORY_INDEX, TAG_INDEX, TIME_INDEX, STATUS_INDEX,
    compute_content_hash, increment_counter, next_entry_id, serialize_entry, status_counter_key,
};

use crate::audit::{AuditEvent, AuditLog};
use crate::categories::CategoryAllowlist;
use crate::embed_handle::EmbedServiceHandle;
use crate::error::ServerError;
use crate::identity::{self, ResolvedIdentity};
use crate::registry::AgentRegistry;

/// Server name reported in MCP initialize handshake.
const SERVER_NAME: &str = "unimatrix";

/// Behavioral instructions for AI agents.
const SERVER_INSTRUCTIONS: &str = "Unimatrix is this project's knowledge engine. Before starting implementation, architecture, or design tasks, search for relevant patterns and conventions using the context tools. Apply what you find. After discovering reusable patterns or making architectural decisions, store them for future reference. Do not store workflow state or process steps.";

/// The central MCP server holding all shared state.
///
/// All fields are Arc-wrapped so Clone is cheap (required by rmcp).
#[derive(Clone)]
pub struct UnimatrixServer {
    /// Async entry store for knowledge operations.
    pub(crate) entry_store: Arc<AsyncEntryStore<StoreAdapter>>,
    /// Async vector store for similarity search.
    pub(crate) vector_store: Arc<AsyncVectorStore<VectorAdapter>>,
    /// Lazy-loading embedding service.
    pub(crate) embed_service: Arc<EmbedServiceHandle>,
    /// Agent registry for identity and capabilities.
    pub(crate) registry: Arc<AgentRegistry>,
    /// Audit log for request tracking.
    pub(crate) audit: Arc<AuditLog>,
    /// Category allowlist for validation.
    pub(crate) categories: Arc<CategoryAllowlist>,
    /// Raw store for combined write transactions (ADR-001).
    pub(crate) store: Arc<Store>,
    /// Tool router generated by the tool_router macro.
    tool_router: ToolRouter<Self>,
    /// Cached server info for MCP handshake.
    server_info: ServerInfo,
}

impl UnimatrixServer {
    /// Create a new server with all subsystems.
    pub fn new(
        entry_store: Arc<AsyncEntryStore<StoreAdapter>>,
        vector_store: Arc<AsyncVectorStore<VectorAdapter>>,
        embed_service: Arc<EmbedServiceHandle>,
        registry: Arc<AgentRegistry>,
        audit: Arc<AuditLog>,
        categories: Arc<CategoryAllowlist>,
        store: Arc<Store>,
    ) -> Self {
        let server_info = ServerInfo {
            server_info: Implementation {
                name: SERVER_NAME.to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
                ..Default::default()
            },
            instructions: Some(SERVER_INSTRUCTIONS.to_string()),
            ..Default::default()
        };

        UnimatrixServer {
            entry_store,
            vector_store,
            embed_service,
            registry,
            audit,
            categories,
            store,
            tool_router: Self::tool_router(),
            server_info,
        }
    }

    /// Resolve an agent identity from tool parameters.
    ///
    /// Convenience method combining extraction and resolution.
    pub fn resolve_agent(
        &self,
        agent_id: &Option<String>,
    ) -> Result<ResolvedIdentity, ServerError> {
        let extracted = identity::extract_agent_id(agent_id);
        identity::resolve_identity(&self.registry, &extracted)
    }

    /// Insert a new entry and write an audit event in a single write transaction.
    ///
    /// Combines entry creation (with all indexes) and audit logging into one
    /// redb write transaction per ADR-001. The HNSW vector insertion happens
    /// after the transaction commits (separate data structure).
    pub(crate) async fn insert_with_audit(
        &self,
        entry: NewEntry,
        embedding: Vec<f32>,
        audit_event: AuditEvent,
    ) -> Result<(u64, EntryRecord), ServerError> {
        let store = Arc::clone(&self.store);
        let audit_log = Arc::clone(&self.audit);

        // Step 1: Combined write transaction (spawn_blocking for redb)
        let (entry_id, record) = tokio::task::spawn_blocking(move || -> Result<(u64, EntryRecord), ServerError> {
            let txn = store.begin_write()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;

            // Generate entry ID
            let id = next_entry_id(&txn)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // Compute content hash
            let content_hash = compute_content_hash(&entry.title, &entry.content);

            // Build EntryRecord
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            let record = EntryRecord {
                id,
                title: entry.title,
                content: entry.content,
                topic: entry.topic,
                category: entry.category,
                tags: entry.tags,
                source: entry.source,
                status: entry.status,
                confidence: 0.0,
                created_at: now,
                updated_at: now,
                last_accessed_at: 0,
                access_count: 0,
                supersedes: None,
                superseded_by: None,
                correction_count: 0,
                embedding_dim: 0,
                created_by: entry.created_by.clone(),
                modified_by: entry.created_by,
                content_hash,
                previous_hash: String::new(),
                version: 1,
                feature_cycle: entry.feature_cycle,
                trust_source: entry.trust_source,
            };

            // Write ENTRIES
            let bytes = serialize_entry(&record)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;
            {
                let mut table = txn.open_table(ENTRIES)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert(id, bytes.as_slice())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write TOPIC_INDEX
            {
                let mut table = txn.open_table(TOPIC_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.topic.as_str(), id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write CATEGORY_INDEX
            {
                let mut table = txn.open_table(CATEGORY_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.category.as_str(), id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write TAG_INDEX (multimap)
            {
                let mut table = txn.open_multimap_table(TAG_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                for tag in &record.tags {
                    table.insert(tag.as_str(), id)
                        .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                }
            }

            // Write TIME_INDEX
            {
                let mut table = txn.open_table(TIME_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.created_at, id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write STATUS_INDEX
            {
                let mut table = txn.open_table(STATUS_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.status as u8, id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Increment status counter
            increment_counter(&txn, status_counter_key(record.status), 1)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // Write audit event in the same transaction
            let audit_event_with_target = AuditEvent {
                target_ids: vec![id],
                ..audit_event
            };
            audit_log.write_in_txn(&txn, audit_event_with_target)?;

            // Commit everything atomically
            txn.commit()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            Ok((id, record))
        }).await.map_err(|e| ServerError::Core(CoreError::JoinError(e.to_string())))??;

        // Step 2: Insert embedding into HNSW index (separate from redb)
        self.vector_store.insert(entry_id, embedding).await
            .map_err(ServerError::Core)?;

        Ok((entry_id, record))
    }
}

#[rmcp::tool_handler]
impl rmcp::ServerHandler for UnimatrixServer {
    fn get_info(&self) -> ServerInfo {
        self.server_info.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    pub(crate) fn make_server() -> UnimatrixServer {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("test.redb");
        let store = Arc::new(Store::open(&path).unwrap());
        std::mem::forget(dir);

        let store_adapter = StoreAdapter::new(Arc::clone(&store));
        let entry_store = Arc::new(AsyncEntryStore::new(Arc::new(store_adapter)));

        // Use a minimal VectorIndex
        let vector_config = unimatrix_core::VectorConfig::default();
        let vector_index = Arc::new(
            unimatrix_core::VectorIndex::new(Arc::clone(&store), vector_config).unwrap(),
        );
        let vector_adapter = VectorAdapter::new(vector_index);
        let vector_store = Arc::new(AsyncVectorStore::new(Arc::new(vector_adapter)));

        let embed_service = EmbedServiceHandle::new();

        let registry = Arc::new(AgentRegistry::new(Arc::clone(&store)).unwrap());
        registry.bootstrap_defaults().unwrap();

        let audit = Arc::new(AuditLog::new(Arc::clone(&store)));
        let categories = Arc::new(CategoryAllowlist::new());

        UnimatrixServer::new(
            entry_store,
            vector_store,
            embed_service,
            registry,
            audit,
            categories,
            Arc::clone(&store),
        )
    }

    #[test]
    fn test_get_info_name() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert_eq!(info.server_info.name, "unimatrix");
    }

    #[test]
    fn test_get_info_version_nonempty() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert!(!info.server_info.version.is_empty());
    }

    #[test]
    fn test_get_info_instructions() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert!(info.instructions.is_some());
        let instructions = info.instructions.unwrap();
        assert!(instructions.contains("knowledge engine"));
        assert!(instructions.contains("search for relevant patterns"));
    }

    #[test]
    fn test_server_is_clone() {
        let server = make_server();
        let _clone = server.clone();
    }

    #[test]
    fn test_resolve_agent_with_id() {
        let server = make_server();
        let identity = server
            .resolve_agent(&Some("human".to_string()))
            .unwrap();
        assert_eq!(identity.agent_id, "human");
        assert_eq!(identity.trust_level, crate::registry::TrustLevel::Privileged);
    }

    #[test]
    fn test_resolve_agent_without_id() {
        let server = make_server();
        let identity = server.resolve_agent(&None).unwrap();
        assert_eq!(identity.agent_id, "anonymous");
    }
}
