//! UnimatrixServer core: state holder and ServerHandler implementation.

use std::sync::Arc;

use redb::ReadableTable;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{Implementation, ServerInfo};
use unimatrix_core::{
    CoreError, EntryRecord, NewEntry, StoreAdapter, Store, VectorAdapter, VectorIndex,
};
use unimatrix_core::async_wrappers::{AsyncEntryStore, AsyncVectorStore};
use unimatrix_store::{
    ENTRIES, TOPIC_INDEX, CATEGORY_INDEX, TAG_INDEX, TIME_INDEX, STATUS_INDEX, VECTOR_MAP, COUNTERS,
    compute_content_hash, deserialize_entry, increment_counter, next_entry_id, serialize_entry,
    status_counter_key, StoreError,
};

use crate::audit::{AuditEvent, AuditLog};
use crate::categories::CategoryAllowlist;
use crate::embed_handle::EmbedServiceHandle;
use crate::error::ServerError;
use crate::identity::{self, ResolvedIdentity};
use crate::registry::AgentRegistry;

/// Server name reported in MCP initialize handshake.
const SERVER_NAME: &str = "unimatrix";

/// Behavioral instructions for AI agents.
const SERVER_INSTRUCTIONS: &str = "Unimatrix is this project's knowledge engine. Before starting implementation, architecture, or design tasks, search for relevant patterns and conventions using the context tools. Apply what you find. After discovering reusable patterns or making architectural decisions, store them for future reference. Do not store workflow state or process steps.";

/// The central MCP server holding all shared state.
///
/// All fields are Arc-wrapped so Clone is cheap (required by rmcp).
#[derive(Clone)]
pub struct UnimatrixServer {
    /// Async entry store for knowledge operations.
    pub(crate) entry_store: Arc<AsyncEntryStore<StoreAdapter>>,
    /// Async vector store for similarity search.
    pub(crate) vector_store: Arc<AsyncVectorStore<VectorAdapter>>,
    /// Lazy-loading embedding service.
    pub(crate) embed_service: Arc<EmbedServiceHandle>,
    /// Agent registry for identity and capabilities.
    pub(crate) registry: Arc<AgentRegistry>,
    /// Audit log for request tracking.
    pub(crate) audit: Arc<AuditLog>,
    /// Category allowlist for validation.
    pub(crate) categories: Arc<CategoryAllowlist>,
    /// Raw store for combined write transactions (ADR-001).
    pub(crate) store: Arc<Store>,
    /// Raw vector index for combined write transactions (GH #14 fix).
    pub(crate) vector_index: Arc<VectorIndex>,
    /// Tool router generated by the tool_router macro.
    tool_router: ToolRouter<Self>,
    /// Cached server info for MCP handshake.
    server_info: ServerInfo,
}

impl UnimatrixServer {
    /// Create a new server with all subsystems.
    pub fn new(
        entry_store: Arc<AsyncEntryStore<StoreAdapter>>,
        vector_store: Arc<AsyncVectorStore<VectorAdapter>>,
        embed_service: Arc<EmbedServiceHandle>,
        registry: Arc<AgentRegistry>,
        audit: Arc<AuditLog>,
        categories: Arc<CategoryAllowlist>,
        store: Arc<Store>,
        vector_index: Arc<VectorIndex>,
    ) -> Self {
        let server_info = ServerInfo {
            server_info: Implementation {
                name: SERVER_NAME.to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
                ..Default::default()
            },
            instructions: Some(SERVER_INSTRUCTIONS.to_string()),
            ..Default::default()
        };

        UnimatrixServer {
            entry_store,
            vector_store,
            embed_service,
            registry,
            audit,
            categories,
            store,
            vector_index,
            tool_router: Self::tool_router(),
            server_info,
        }
    }

    /// Resolve an agent identity from tool parameters.
    ///
    /// Convenience method combining extraction and resolution.
    pub fn resolve_agent(
        &self,
        agent_id: &Option<String>,
    ) -> Result<ResolvedIdentity, ServerError> {
        let extracted = identity::extract_agent_id(agent_id);
        identity::resolve_identity(&self.registry, &extracted)
    }

    /// Insert a new entry and write an audit event in a single write transaction.
    ///
    /// Combines entry creation (with all indexes), VECTOR_MAP write, and audit
    /// logging into one redb write transaction per ADR-001. The HNSW vector
    /// insertion happens after the transaction commits (separate data structure).
    ///
    /// GH #14 fix: VECTOR_MAP is now written atomically with the entry.
    pub(crate) async fn insert_with_audit(
        &self,
        entry: NewEntry,
        embedding: Vec<f32>,
        audit_event: AuditEvent,
    ) -> Result<(u64, EntryRecord), ServerError> {
        let store = Arc::clone(&self.store);
        let audit_log = Arc::clone(&self.audit);

        // Allocate HNSW data_id before the transaction (GH #14)
        let data_id = self.vector_index.allocate_data_id();

        // Step 1: Combined write transaction (spawn_blocking for redb)
        let (entry_id, record) = tokio::task::spawn_blocking(move || -> Result<(u64, EntryRecord), ServerError> {
            let txn = store.begin_write()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;

            // Generate entry ID
            let id = next_entry_id(&txn)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // Compute content hash
            let content_hash = compute_content_hash(&entry.title, &entry.content);

            // Build EntryRecord
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            let record = EntryRecord {
                id,
                title: entry.title,
                content: entry.content,
                topic: entry.topic,
                category: entry.category,
                tags: entry.tags,
                source: entry.source,
                status: entry.status,
                confidence: 0.0,
                created_at: now,
                updated_at: now,
                last_accessed_at: 0,
                access_count: 0,
                supersedes: None,
                superseded_by: None,
                correction_count: 0,
                embedding_dim: 0,
                created_by: entry.created_by.clone(),
                modified_by: entry.created_by,
                content_hash,
                previous_hash: String::new(),
                version: 1,
                feature_cycle: entry.feature_cycle,
                trust_source: entry.trust_source,
            };

            // Write ENTRIES
            let bytes = serialize_entry(&record)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;
            {
                let mut table = txn.open_table(ENTRIES)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert(id, bytes.as_slice())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write TOPIC_INDEX
            {
                let mut table = txn.open_table(TOPIC_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.topic.as_str(), id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write CATEGORY_INDEX
            {
                let mut table = txn.open_table(CATEGORY_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.category.as_str(), id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write TAG_INDEX (multimap)
            {
                let mut table = txn.open_multimap_table(TAG_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                for tag in &record.tags {
                    table.insert(tag.as_str(), id)
                        .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                }
            }

            // Write TIME_INDEX
            {
                let mut table = txn.open_table(TIME_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.created_at, id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write STATUS_INDEX
            {
                let mut table = txn.open_table(STATUS_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((record.status as u8, id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Write VECTOR_MAP in the same transaction (GH #14 fix)
            {
                let mut table = txn.open_table(VECTOR_MAP)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert(id, data_id)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // Increment status counter
            increment_counter(&txn, status_counter_key(record.status), 1)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // Write audit event in the same transaction
            let audit_event_with_target = AuditEvent {
                target_ids: vec![id],
                ..audit_event
            };
            audit_log.write_in_txn(&txn, audit_event_with_target)?;

            // Commit everything atomically
            txn.commit()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            Ok((id, record))
        }).await.map_err(|e| ServerError::Core(CoreError::JoinError(e.to_string())))??;

        // Step 2: Insert into HNSW only (VECTOR_MAP already committed)
        self.vector_index.insert_hnsw_only(entry_id, data_id, &embedding)
            .map_err(|e| ServerError::Core(CoreError::Vector(e)))?;

        Ok((entry_id, record))
    }

    /// Correct an existing entry: deprecate original, create correction, both
    /// in a single write transaction with audit.
    ///
    /// Returns (deprecated_original, new_correction).
    pub(crate) async fn correct_with_audit(
        &self,
        original_id: u64,
        correction_entry: NewEntry,
        embedding: Vec<f32>,
        audit_event: AuditEvent,
    ) -> Result<(EntryRecord, EntryRecord), ServerError> {
        let store = Arc::clone(&self.store);
        let audit_log = Arc::clone(&self.audit);
        let data_id = self.vector_index.allocate_data_id();

        let (deprecated_original, new_correction) = tokio::task::spawn_blocking(move || -> Result<(EntryRecord, EntryRecord), ServerError> {
            let txn = store.begin_write()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;

            // 1. Read and validate original entry
            let original_bytes = {
                let table = txn.open_table(ENTRIES)
                    .map_err(|e| ServerError::Core(CoreError::Store(StoreError::from(e))))?;
                let guard = table.get(original_id)
                    .map_err(|e| ServerError::Core(CoreError::Store(StoreError::from(e))))?
                    .ok_or(ServerError::Core(CoreError::Store(StoreError::EntryNotFound(original_id))))?;
                guard.value().to_vec()
            };
            let mut original = deserialize_entry(&original_bytes)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // 2. Verify original is not already deprecated
            if original.status == unimatrix_store::Status::Deprecated {
                return Err(ServerError::InvalidInput {
                    field: "original_id".to_string(),
                    reason: "cannot correct a deprecated entry".to_string(),
                });
            }

            // 3. Generate new entry ID
            let new_id = next_entry_id(&txn)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // 4. Deprecate original
            let old_status = original.status;
            original.status = unimatrix_store::Status::Deprecated;
            original.superseded_by = Some(new_id);
            original.correction_count += 1;
            original.updated_at = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();

            // 5. Serialize and overwrite original in ENTRIES
            let original_bytes = serialize_entry(&original)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;
            {
                let mut table = txn.open_table(ENTRIES)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert(original_id, original_bytes.as_slice())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // 6. Update STATUS_INDEX for original
            {
                let mut table = txn.open_table(STATUS_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.remove((old_status as u8, original_id))
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((unimatrix_store::Status::Deprecated as u8, original_id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // 7. Update status counters for original
            decrement_counter(&txn, status_counter_key(old_status), 1)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;
            increment_counter(&txn, status_counter_key(unimatrix_store::Status::Deprecated), 1)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // 8. Build correction EntryRecord
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            let content_hash = compute_content_hash(&correction_entry.title, &correction_entry.content);
            let correction = EntryRecord {
                id: new_id,
                title: correction_entry.title,
                content: correction_entry.content,
                topic: correction_entry.topic,
                category: correction_entry.category,
                tags: correction_entry.tags,
                source: correction_entry.source,
                status: correction_entry.status,
                confidence: 0.0,
                created_at: now,
                updated_at: now,
                last_accessed_at: 0,
                access_count: 0,
                supersedes: Some(original_id),
                superseded_by: None,
                correction_count: 0,
                embedding_dim: 0,
                created_by: correction_entry.created_by.clone(),
                modified_by: correction_entry.created_by,
                content_hash,
                previous_hash: String::new(),
                version: 1,
                feature_cycle: correction_entry.feature_cycle,
                trust_source: correction_entry.trust_source,
            };

            // 9. Write correction to ENTRIES
            let correction_bytes = serialize_entry(&correction)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;
            {
                let mut table = txn.open_table(ENTRIES)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert(new_id, correction_bytes.as_slice())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // 10. Write all indexes for correction
            {
                let mut table = txn.open_table(TOPIC_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((correction.topic.as_str(), new_id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }
            {
                let mut table = txn.open_table(CATEGORY_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((correction.category.as_str(), new_id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }
            {
                let mut table = txn.open_multimap_table(TAG_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                for tag in &correction.tags {
                    table.insert(tag.as_str(), new_id)
                        .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                }
            }
            {
                let mut table = txn.open_table(TIME_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((correction.created_at, new_id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }
            {
                let mut table = txn.open_table(STATUS_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((correction.status as u8, new_id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // 11. Increment status counter for correction
            increment_counter(&txn, status_counter_key(correction.status), 1)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // 12. Write VECTOR_MAP for correction
            {
                let mut table = txn.open_table(VECTOR_MAP)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert(new_id, data_id)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // 13. Write audit event with both IDs
            let audit_with_ids = AuditEvent {
                target_ids: vec![original_id, new_id],
                ..audit_event
            };
            audit_log.write_in_txn(&txn, audit_with_ids)?;

            // 14. Commit
            txn.commit()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;

            Ok((original, correction))
        }).await.map_err(|e| ServerError::Core(CoreError::JoinError(e.to_string())))??;

        // HNSW insert for the correction (after commit)
        self.vector_index.insert_hnsw_only(new_correction.id, data_id, &embedding)
            .map_err(|e| ServerError::Core(CoreError::Vector(e)))?;

        Ok((deprecated_original, new_correction))
    }

    /// Deprecate an entry: set status to Deprecated in a single write transaction
    /// with audit. Idempotent: already-deprecated entries return immediately.
    pub(crate) async fn deprecate_with_audit(
        &self,
        entry_id: u64,
        reason: Option<String>,
        audit_event: AuditEvent,
    ) -> Result<EntryRecord, ServerError> {
        let store = Arc::clone(&self.store);
        let audit_log = Arc::clone(&self.audit);

        let record = tokio::task::spawn_blocking(move || -> Result<EntryRecord, ServerError> {
            let txn = store.begin_write()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;

            // 1. Read existing entry
            let entry_bytes = {
                let table = txn.open_table(ENTRIES)
                    .map_err(|e| ServerError::Core(CoreError::Store(StoreError::from(e))))?;
                let guard = table.get(entry_id)
                    .map_err(|e| ServerError::Core(CoreError::Store(StoreError::from(e))))?
                    .ok_or(ServerError::Core(CoreError::Store(StoreError::EntryNotFound(entry_id))))?;
                guard.value().to_vec()
            };
            let mut record = deserialize_entry(&entry_bytes)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // 2. Idempotency check: already deprecated -> return as-is
            if record.status == unimatrix_store::Status::Deprecated {
                return Ok(record);
            }

            // 3. Update status
            let old_status = record.status;
            record.status = unimatrix_store::Status::Deprecated;
            record.updated_at = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();

            // 4. Serialize and overwrite in ENTRIES
            let bytes = serialize_entry(&record)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;
            {
                let mut table = txn.open_table(ENTRIES)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert(entry_id, bytes.as_slice())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // 5. Update STATUS_INDEX
            {
                let mut table = txn.open_table(STATUS_INDEX)
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.remove((old_status as u8, entry_id))
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
                table.insert((unimatrix_store::Status::Deprecated as u8, entry_id), ())
                    .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            }

            // 6. Update status counters
            decrement_counter(&txn, status_counter_key(old_status), 1)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;
            increment_counter(&txn, status_counter_key(unimatrix_store::Status::Deprecated), 1)
                .map_err(|e| ServerError::Core(CoreError::Store(e)))?;

            // 7. Write audit event with reason in detail
            let detail = match &reason {
                Some(r) => format!("deprecated entry #{entry_id}: {r}"),
                None => format!("deprecated entry #{entry_id}"),
            };
            let audit_with_detail = AuditEvent {
                target_ids: vec![entry_id],
                detail,
                ..audit_event
            };
            audit_log.write_in_txn(&txn, audit_with_detail)?;

            // 8. Commit
            txn.commit()
                .map_err(|e| ServerError::Core(CoreError::Store(e.into())))?;
            Ok(record)
        }).await.map_err(|e| ServerError::Core(CoreError::JoinError(e.to_string())))??;

        Ok(record)
    }
}

/// Decrement a counter value, saturating at 0.
fn decrement_counter(
    txn: &redb::WriteTransaction,
    key: &str,
    amount: u64,
) -> Result<(), unimatrix_store::StoreError> {
    use redb::ReadableTable;
    let mut table = txn.open_table(COUNTERS)
        .map_err(|e| unimatrix_store::StoreError::from(e))?;
    let current = match table.get(key)
        .map_err(|e| unimatrix_store::StoreError::from(e))?
    {
        Some(guard) => guard.value(),
        None => 0,
    };
    table.insert(key, current.saturating_sub(amount))
        .map_err(|e| unimatrix_store::StoreError::from(e))?;
    Ok(())
}

#[rmcp::tool_handler]
impl rmcp::ServerHandler for UnimatrixServer {
    fn get_info(&self) -> ServerInfo {
        self.server_info.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    pub(crate) fn make_server() -> UnimatrixServer {
        let dir = tempfile::TempDir::new().unwrap();
        let path = dir.path().join("test.redb");
        let store = Arc::new(Store::open(&path).unwrap());
        std::mem::forget(dir);

        let store_adapter = StoreAdapter::new(Arc::clone(&store));
        let entry_store = Arc::new(AsyncEntryStore::new(Arc::new(store_adapter)));

        // Use a minimal VectorIndex
        let vector_config = unimatrix_core::VectorConfig::default();
        let vector_index = Arc::new(
            unimatrix_core::VectorIndex::new(Arc::clone(&store), vector_config).unwrap(),
        );
        let vector_adapter = VectorAdapter::new(Arc::clone(&vector_index));
        let vector_store = Arc::new(AsyncVectorStore::new(Arc::new(vector_adapter)));

        let embed_service = EmbedServiceHandle::new();

        let registry = Arc::new(AgentRegistry::new(Arc::clone(&store)).unwrap());
        registry.bootstrap_defaults().unwrap();

        let audit = Arc::new(AuditLog::new(Arc::clone(&store)));
        let categories = Arc::new(CategoryAllowlist::new());

        UnimatrixServer::new(
            entry_store,
            vector_store,
            embed_service,
            registry,
            audit,
            categories,
            Arc::clone(&store),
            vector_index,
        )
    }

    #[test]
    fn test_get_info_name() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert_eq!(info.server_info.name, "unimatrix");
    }

    #[test]
    fn test_get_info_version_nonempty() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert!(!info.server_info.version.is_empty());
    }

    #[test]
    fn test_get_info_instructions() {
        let server = make_server();
        let info = rmcp::ServerHandler::get_info(&server);
        assert!(info.instructions.is_some());
        let instructions = info.instructions.unwrap();
        assert!(instructions.contains("knowledge engine"));
        assert!(instructions.contains("search for relevant patterns"));
    }

    #[test]
    fn test_server_is_clone() {
        let server = make_server();
        let _clone = server.clone();
    }

    #[test]
    fn test_resolve_agent_with_id() {
        let server = make_server();
        let identity = server
            .resolve_agent(&Some("human".to_string()))
            .unwrap();
        assert_eq!(identity.agent_id, "human");
        assert_eq!(identity.trust_level, crate::registry::TrustLevel::Privileged);
    }

    #[test]
    fn test_resolve_agent_without_id() {
        let server = make_server();
        let identity = server.resolve_agent(&None).unwrap();
        assert_eq!(identity.agent_id, "anonymous");
    }
}
