// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * F4b: client-declared cycle attribution (contract, not inference).
 *
 * Presence on an [`ImplantEvent`] (via [`ImplantEvent::cycle_stamp`]) means the row
 * attributes from the stamp, not the heuristic chain (ADR-004): the server's precedence
 * becomes structural (presence-gated), not re-orderable. `topic` is the declared feature
 * id; `phase` is the optional declared phase (omitted when the client tracker file has no
 * phase). Additive/frozen-F1: rides [`ImplantEvent`] under `skip_serializing_if`, so it
 * never appears in pre-existing fixtures and needs no `deny_unknown_fields`.
 *
 * The 7th ts-rs export. Verified dual-sided (Rust↔TS) by AC-02.
 */
export type CycleStampPayload = { 
/**
 * Declared feature id (e.g. "vnc-030"). Required — a stamp with no topic is meaningless.
 */
topic: string, 
/**
 * Declared phase (e.g. "delivery"). Omitted when the client tracker has no phase.
 */
phase?: string | null, };
