// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A knowledge entry returned in search/briefing results.
 */
export type EntryPayload = { id: bigint, title: string, content: string, confidence: number, similarity: number, category: string, };
