// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImplantEvent } from "./ImplantEvent";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Request sent from hook processes to the UDS listener.
 *
 * Uses `#[serde(tag = "type")]` for JSON routing per ADR-005.
 */
export type HookRequest = { "type": "Ping" } | { "type": "SessionRegister", session_id: string, cwd: string, agent_role: string | null, feature: string | null, } | { "type": "SessionClose", session_id: string, outcome: string | null, duration_secs: bigint, } | { "type": "RecordEvent", 
/**
 * Type of event (e.g., "tool_use", "context_read").
 */
event_type: string, 
/**
 * Session that generated the event.
 */
session_id: string, 
/**
 * Unix timestamp (seconds since epoch).
 */
timestamp: bigint, 
/**
 * Event-specific data.
 */
payload: JsonValue, 
/**
 * Hook-side topic signal extracted from event content (col-017).
 * Used for session-level feature attribution via majority vote.
 */
topic_signal?: string | null, 
/**
 * Provider identity propagated from HookInput.provider through normalization.
 * Non-None for all events processed through the normalization layer.
 * None for events deserialized from wire frames that predate vnc-013 (backward compat).
 *
 * `skip_serializing_if = "Option::is_none"`: Claude Code events without --provider
 * produce wire frames without this field; the listener handles missing field as None.
 */
provider?: string | null, } | { "type": "RecordEvents", events: Array<ImplantEvent>, } | { "type": "ContextSearch", query: string, session_id: string | null, role: string | null, task: string | null, feature: string | null, k: number | null, max_tokens: number | null, 
/**
 * Originating hook event type; `None` is treated as `"UserPromptSubmit"` by
 * `dispatch_request`. Set to `Some("SubagentStart")` by the SubagentStart arm
 * in `hook.rs`. See ADR-001 crt-027.
 */
source?: string | null, 
/**
 * HTTP-`Accept` mirror for server-side preformatted sync responses (vnc-027
 * ADR-001 §1). Set ONLY by `transport-uds.js` at serialization time, value
 * `Some("text/plain")`. `hook.rs` construction sites pass `None` (mechanical
 * edit, approved variance). `skip_serializing_if` keeps `None` absent on the
 * wire, so frozen-hook frames stay byte-identical (AC-11).
 */
accept?: string | null, } | { "type": "Briefing", role: string, task: string, feature: string | null, max_tokens: number | null, } | { "type": "CompactPayload", session_id: string, 
/**
 * Reserved for col-010: once INJECTION_LOG persists to the database, the hook
 * process can populate this from disk after a server restart, giving
 * the server richer input than the briefing fallback. Currently empty
 * (server tracks injection history in-memory via SessionRegistry).
 */
injected_entry_ids: Array<bigint>, role: string | null, feature: string | null, token_limit: number | null, 
/**
 * Forward-compatible transcript excerpt for PreCompact restoration (#670).
 * Day 1: always None over HTTP; handle_compact_payload ignores it.
 * Future clients (or hook-remote CLI) can populate this field to send
 * transcript data for server-side restoration. See ADR-005 vnc-022.
 */
transcript_excerpt?: string | null, 
/**
 * HTTP-`Accept` mirror for server-side preformatted sync responses (vnc-027
 * ADR-001 §1). Set ONLY by `transport-uds.js` at serialization time, value
 * `Some("text/plain")`. `hook.rs` construction sites pass `None` (mechanical
 * edit, approved variance). `skip_serializing_if` keeps `None` absent on the
 * wire, so frozen-hook frames stay byte-identical (AC-11).
 */
accept?: string | null, };
