// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryPayload } from "./EntryPayload";

/**
 * Response sent from the UDS listener back to hook processes.
 *
 * Uses `#[serde(tag = "type")]` for JSON routing per ADR-005.
 */
export type HookResponse = { "type": "Pong", server_version: string, } | { "type": "Ack" } | { "type": "Error", code: number, message: string, } | { "type": "Entries", items: Array<EntryPayload>, total_tokens: number, } | { "type": "BriefingContent", content: string, token_count: number, } | { "type": "Text", body: string, };
