// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Represents the JSON blob that Claude Code pipes to hook processes on stdin.
 *
 * All fields use `#[serde(default)]` for maximum defensive parsing per ADR-006.
 * Unknown fields are captured by the `extra` flatten field.
 */
export type HookInput = { 
/**
 * The hook event name (e.g., "PreToolUse", "PostToolUse", "Stop").
 */
hook_event_name: string, 
/**
 * Claude Code session identifier.
 */
session_id: string | null, 
/**
 * Current working directory of the Claude Code session.
 */
cwd: string | null, 
/**
 * Path to the session transcript file.
 */
transcript_path: string | null, 
/**
 * User prompt text (UserPromptSubmit events only).
 */
prompt: string | null, 
/**
 * Originating LLM provider. Populated by hook::run() after normalize_event_name(),
 * NOT from stdin JSON. `#[serde(default)]` ensures existing Claude Code hook JSON
 * (which omits this field) deserializes to None without error (NFR-05, ADR-002).
 *
 * Valid values: "claude-code" | "gemini-cli" | "codex-cli" | None
 */
provider: string | null, 
/**
 * Gemini CLI structured MCP context field. Present in BeforeTool and AfterTool
 * payloads. Structure: { "server_name": str, "tool_name": str, "url": str }.
 * Also captured by the `extra` flatten, but the named field enables typed access
 * in build_cycle_event_or_fallthrough() without stringly-typed extra access (ADR-003).
 *
 * Claude Code and Codex payloads omit this field; serde(default) → None.
 */
mcp_context: JsonValue | null, } & (number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null);
