// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single event recorded by a hook process.
 *
 * transcript_delta precedence (vnc-024 FR-15 / SR-06, documentary only): when both a
 * streamed `transcript_delta` (`event_type == TRANSCRIPT_DELTA_EVENT`, `payload` =
 * [`TranscriptDeltaPayload`]) and a legacy `CompactPayload.transcript_excerpt` are present,
 * the streamed delta is the authoritative forward path and supersedes the excerpt (ass-069).
 * F1 documents this precedence; the merge logic is #670. No merge code is added here.
 */
export type ImplantEvent = { 
/**
 * Type of event (e.g., "tool_use", "context_read").
 */
event_type: string, 
/**
 * Session that generated the event.
 */
session_id: string, 
/**
 * Unix timestamp (seconds since epoch).
 */
timestamp: bigint, 
/**
 * Event-specific data.
 */
payload: JsonValue, 
/**
 * Hook-side topic signal extracted from event content (col-017).
 * Used for session-level feature attribution via majority vote.
 */
topic_signal?: string | null, 
/**
 * Provider identity propagated from HookInput.provider through normalization.
 * Non-None for all events processed through the normalization layer.
 * None for events deserialized from wire frames that predate vnc-013 (backward compat).
 *
 * `skip_serializing_if = "Option::is_none"`: Claude Code events without --provider
 * produce wire frames without this field; the listener handles missing field as None.
 */
provider?: string | null, };
