// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed payload for a `transcript_delta` event (`event_type == TRANSCRIPT_DELTA_EVENT`).
 *
 * A client-streamed raw transcript span: `offset` is the byte offset of this span within
 * the session transcript and `bytes` is the verbatim text. This is **not** a new wire
 * carrier — the value still rides [`ImplantEvent::payload`] (`serde_json::Value`) unchanged.
 * The struct exists to (a) give the one genuinely-new field a typed cross-language binding
 * (`bindings/TranscriptDeltaPayload.ts`) so the TS client does not hand-mirror it, and
 * (b) be the deserialization shape the accept-and-drop guard parses into (vnc-024 ADR-004).
 *
 * Raw transcript bytes may contain secrets; they are accepted-and-dropped, never persisted
 * (principle 8). The 6th ts-rs export. Verified dual-sided (Rust↔TS) by AC-11.
 */
export type TranscriptDeltaPayload = { 
/**
 * Byte offset of this span within the session transcript.
 */
offset: bigint, 
/**
 * Verbatim transcript text for this span.
 */
bytes: string, };
