"use strict";

const fs = require("fs");
const path = require("path");

/**
 * C9 — Non-clobbering, additive OpenCode provisioning (ADR-006, vnc-049).
 *
 * `unimatrix init` gains an OpenCode branch that provisions the C1 plugin
 * artifact WITHOUT regressing C10 retrieval. The `mcp.unimatrix` server entry,
 * the local STDIO command, the Ollama `provider` block, permissions, and every
 * non-Unimatrix key in `opencode.json` are the C17 regression sentinel (#5582,
 * AC-05/SR-08) and are preserved byte-for-byte: this module NEVER reads or
 * rewrites those stanzas, it only appends its own additive entries.
 *
 * Unlike the rest of init (which is the one loud checkpoint and THROWS on bad
 * input), the OpenCode branch is best-effort / fail-safe: a malformed config or
 * an fs error is warned-and-skipped, never thrown, so it can never corrupt the
 * file or clobber retrieval (ADR-006 §Error handling, mirrors
 * cleanStaleRemoteSubtree). R-15: the plugin identity is a fixed constant — no
 * path is ever derived from (or followed out of) untrusted user config, and
 * every write target is asserted to live inside the project dir.
 */

/**
 * Artifact identity shared with C1 (`opencode-plugin/`). C1 and C9 MUST agree
 * on this name (C1 pseudocode §Config note). The npm package is referenced by
 * the `.opencode/package.json` dep and the `.opencode/plugins/` re-export shim;
 * OpenCode runs `bun install` at startup and auto-loads the plugin dir.
 */
const PLUGIN_PACKAGE = "@dug-21/unimatrix-opencode-plugin";
const PLUGIN_EXPORT = "UnimatrixObservePlugin";
const PLUGIN_ENTRY_FILE = "unimatrix.js";
/** Used only if the host package version cannot be read (fail-safe). */
const PLUGIN_VERSION_FALLBACK = "*";

/**
 * The re-export shim dropped into `.opencode/plugins/`. It is a self-contained
 * ESM file that re-exports the real plugin from the provisioned npm dep, so the
 * installer needs no copy of the C1 source tree at install time and the shim
 * content is stable (idempotent — re-running writes identical bytes).
 */
const PLUGIN_SHIM_CONTENT =
  "// Generated by `unimatrix init` (vnc-049, ADR-006). Do not edit.\n" +
  "export { " +
  PLUGIN_EXPORT +
  ' } from "' +
  PLUGIN_PACKAGE +
  '";\n';

/**
 * Detect OpenCode by the presence of `opencode.json` or `.opencode/`
 * (ADR-006 §1). Fail-safe: any stat error is treated as "not present".
 *
 * @param {string} dir - Absolute project root.
 * @returns {boolean} true iff OpenCode markers are present.
 */
function detectsOpenCode(dir) {
  return exists(path.join(dir, "opencode.json")) || exists(path.join(dir, ".opencode"));
}

/**
 * Best-effort existence check (never throws).
 * @param {string} p
 * @returns {boolean}
 */
function exists(p) {
  try {
    return fs.existsSync(p);
  } catch (_err) {
    return false;
  }
}

/**
 * R-15 containment guard: resolve `target` and assert it lives inside `dir`.
 * Blocks a symlinked or traversal-crafted path from escaping the project. The
 * installer only ever writes to fixed constant subpaths, so a failure here is a
 * hostile/misconfigured tree — skip that write, never follow it.
 *
 * @param {string} dir - Absolute project root.
 * @param {string} target - Path to be written.
 * @returns {boolean} true iff `target` is within `dir`.
 */
function isWithinProject(dir, target) {
  const root = path.resolve(dir);
  const resolved = path.resolve(target);
  return resolved === root || resolved.startsWith(root + path.sep);
}

/**
 * Detect the indentation of an existing JSON document so re-serialization does
 * not reformat preserved stanzas (ADR-006: mutate minimally). Defaults to two
 * spaces — the formatting the rest of init writes.
 *
 * @param {string} raw - Raw file contents.
 * @returns {number|string} Indent arg for JSON.stringify.
 */
function detectIndent(raw) {
  const m = /\n([ \t]+)"/.exec(raw);
  if (!m) {
    return 2;
  }
  return m[1].indexOf("\t") >= 0 ? "\t" : m[1].length;
}

/**
 * Read + parse a JSON file WITHOUT throwing (best-effort). Distinguishes
 * absent (ok, empty) from malformed (skip that leg, preserve the file).
 *
 * @param {string} filePath
 * @returns {{ present:boolean, parsed:(object|null), raw:string, malformed:boolean }}
 */
function readJsonSafe(filePath) {
  let raw;
  try {
    raw = fs.readFileSync(filePath, "utf8");
  } catch (_err) {
    return { present: false, parsed: null, raw: "", malformed: false };
  }
  const trimmed = raw.trim();
  if (trimmed === "") {
    return { present: true, parsed: {}, raw: raw, malformed: false };
  }
  try {
    const parsed = JSON.parse(trimmed);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return { present: true, parsed: null, raw: raw, malformed: true };
    }
    return { present: true, parsed: parsed, raw: raw, malformed: false };
  } catch (_err) {
    return { present: true, parsed: null, raw: raw, malformed: true };
  }
}

/**
 * Resolve the plugin dep version from the host package (`@dug-21/unimatrix`),
 * pinned as a caret range. Fail-safe: unreadable package.json → wildcard.
 *
 * @returns {string}
 */
function resolvePluginVersion() {
  try {
    const pkgPath = path.join(__dirname, "..", "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    if (pkg && typeof pkg.version === "string" && pkg.version) {
      return "^" + pkg.version;
    }
  } catch (_err) {
    // fall through to fallback
  }
  return PLUGIN_VERSION_FALLBACK;
}

/**
 * Idempotent, non-clobbering append of `entry` to a `plugin` array
 * (nan-004 dedupe principle, #1195). Mutates `config`; returns true iff changed.
 *
 * @param {object} config
 * @param {string} entry
 * @returns {boolean}
 */
function appendPluginEntry(config, entry) {
  if (!Array.isArray(config.plugin)) {
    // Only initialize when absent; never clobber a non-array `plugin` value.
    if (config.plugin !== undefined) {
      return false;
    }
    config.plugin = [];
  }
  if (config.plugin.includes(entry)) {
    return false;
  }
  config.plugin.push(entry);
  return true;
}

/**
 * Idempotent, non-clobbering add of the plugin dep to a `package.json` object.
 * Mutates `pkg`; returns true iff changed. Existing deps are preserved; an
 * already-present dep (any version) is left untouched (no version drift).
 *
 * @param {object} pkg
 * @param {string} name
 * @param {string} version
 * @returns {boolean}
 */
function mergePackageDep(pkg, name, version) {
  if (!pkg.dependencies || typeof pkg.dependencies !== "object" || Array.isArray(pkg.dependencies)) {
    pkg.dependencies = {};
  }
  if (Object.prototype.hasOwnProperty.call(pkg.dependencies, name)) {
    return false;
  }
  pkg.dependencies[name] = version;
  return true;
}

/**
 * Write JSON with stable formatting (best-effort; caller guards containment).
 *
 * @param {string} filePath
 * @param {object} obj
 * @param {number|string} indent
 */
function writeJson(filePath, obj, indent) {
  fs.writeFileSync(filePath, JSON.stringify(obj, null, indent) + "\n", "utf8");
}

/**
 * Mode A (ADR-006 §2, primary): drop the re-export shim into
 * `.opencode/plugins/` and add the plugin dep to `.opencode/package.json`.
 * Touches ONLY the `.opencode/` surface — never `opencode.json` — so the
 * retrieval sentinel is untouched on this leg. Idempotent.
 *
 * @param {string} dir - Absolute project root.
 * @param {boolean} dryRun
 * @param {string[]} actions - Mutated with a line per action.
 */
function provisionPluginDir(dir, dryRun, actions) {
  const pluginsDir = path.join(dir, ".opencode", "plugins");
  const shimPath = path.join(pluginsDir, PLUGIN_ENTRY_FILE);
  const pkgPath = path.join(dir, ".opencode", "package.json");

  if (!isWithinProject(dir, shimPath) || !isWithinProject(dir, pkgPath)) {
    actions.push("Note: skipped OpenCode plugin dir (path escapes project)");
    return;
  }

  // Shim file (idempotent: identical bytes on re-run).
  const shimExists = exists(shimPath);
  if (dryRun) {
    actions.push("[dry-run] Would provision OpenCode plugin shim: .opencode/plugins/" + PLUGIN_ENTRY_FILE);
  } else {
    fs.mkdirSync(pluginsDir, { recursive: true });
    fs.writeFileSync(shimPath, PLUGIN_SHIM_CONTENT, "utf8");
    actions.push(
      (shimExists ? "Updated" : "Provisioned") +
        " OpenCode plugin shim: .opencode/plugins/" +
        PLUGIN_ENTRY_FILE
    );
  }

  // .opencode/package.json dep (create or non-clobber merge).
  const version = resolvePluginVersion();
  const read = readJsonSafe(pkgPath);
  if (read.malformed) {
    actions.push("Note: .opencode/package.json malformed — dep not added (preserved as-is)");
    return;
  }
  const pkg = read.parsed || {};
  const changed = mergePackageDep(pkg, PLUGIN_PACKAGE, version);
  if (!changed) {
    actions.push("OpenCode plugin dep already present (no change)");
    return;
  }
  if (dryRun) {
    actions.push("[dry-run] Would add OpenCode plugin dep to .opencode/package.json");
  } else {
    const indent = read.present ? detectIndent(read.raw) : 2;
    writeJson(pkgPath, pkg, indent);
    actions.push("Added OpenCode plugin dep to .opencode/package.json");
  }
}

/**
 * Mode B (ADR-006 §2, alternate — documented): append the plugin package to the
 * `plugin:[]` array in `opencode.json`. Additive-only: parses, mutates ONLY the
 * `plugin` key, and re-serializes at the file's own indentation so preserved
 * stanzas (`mcp.unimatrix`, the Ollama `provider` block, permissions, all
 * non-Unimatrix keys) are byte-for-byte identical (AC-05b, R-08). No opencode.json
 * → skip (Mode A still provisioned the dir). Malformed → warn + skip, never
 * clobber (R-15). Idempotent (nan-004 dedupe).
 *
 * @param {string} dir - Absolute project root.
 * @param {boolean} dryRun
 * @param {string[]} actions - Mutated with a line per action.
 */
function provisionPluginArray(dir, dryRun, actions) {
  const cfgPath = path.join(dir, "opencode.json");
  if (!isWithinProject(dir, cfgPath)) {
    return;
  }
  const read = readJsonSafe(cfgPath);
  if (!read.present) {
    return; // no opencode.json → nothing to append; Mode A covers provisioning.
  }
  if (read.malformed) {
    actions.push("Note: opencode.json malformed — plugin array not touched (preserved as-is)");
    return;
  }
  const config = read.parsed || {};
  const changed = appendPluginEntry(config, PLUGIN_PACKAGE);
  if (!changed) {
    actions.push("OpenCode plugin array entry already present (no change)");
    return;
  }
  if (dryRun) {
    actions.push("[dry-run] Would append OpenCode plugin to opencode.json plugin[]");
  } else {
    writeJson(cfgPath, config, detectIndent(read.raw));
    actions.push("Appended OpenCode plugin to opencode.json plugin[]");
  }
}

/**
 * Provision the OpenCode plugin (both modes). Fail-safe: the whole body is
 * wrapped so a failure warns-and-continues instead of aborting init (ADR-006).
 * Assumes detection already passed.
 *
 * @param {string} dir - Absolute project root.
 * @param {object} [options] - { dryRun?: boolean }
 * @returns {string[]} Actions taken.
 */
function provisionOpenCode(dir, options) {
  const dryRun = (options && options.dryRun) || false;
  const actions = [];
  try {
    provisionPluginDir(dir, dryRun, actions);
    provisionPluginArray(dir, dryRun, actions);
  } catch (e) {
    // Best-effort: OpenCode provisioning must never break init or clobber
    // retrieval. Message carries no secret (paths only, no token).
    actions.push("Note: OpenCode provisioning skipped (" + e.message + ")");
  }
  return actions;
}

/**
 * Detection-gated entry point for init.js (ADR-005 thin wiring). Returns no
 * actions when OpenCode is not detected (branch skipped).
 *
 * @param {string} dir - Absolute project root.
 * @param {object} [options] - { dryRun?: boolean }
 * @returns {string[]} Actions taken (empty when not detected).
 */
function maybeProvisionOpenCode(dir, options) {
  try {
    if (!detectsOpenCode(dir)) {
      return [];
    }
  } catch (_err) {
    return [];
  }
  return provisionOpenCode(dir, options);
}

module.exports = {
  detectsOpenCode,
  provisionOpenCode,
  maybeProvisionOpenCode,
  appendPluginEntry,
  mergePackageDep,
  isWithinProject,
  detectIndent,
  readJsonSafe,
  resolvePluginVersion,
  PLUGIN_PACKAGE,
  PLUGIN_EXPORT,
  PLUGIN_ENTRY_FILE,
  PLUGIN_SHIM_CONTENT,
};
