//! OpenCode provider-arm parity goldens (vnc-049 C8, ADR-004; col-022 split-brain).
//!
//! Extends the vnc-026 corpus (ADR-001 oracle/golden/drift) with the OpenCode
//! normalization arm that the JS mirror (`normalize.js`, C3) must match
//! byte-for-byte. The shipped Rust `hook/opencode.rs` (C2) is the oracle
//! (#4751/#5754); this module regenerates `opencode-arm-goldens.json` from the
//! REAL arm functions so the CI zero-diff gate (`scripts/check-parity-drift.sh`)
//! turns red the moment `hook/opencode.rs` changes without a regenerate, and the
//! JS consumer suite (`parity-opencode-arm.test.js`) turns red the moment
//! `normalize.js` diverges from the committed golden. Editing EITHER arm alone
//! breaks a gate — the whole point of the col-022 guard (NFR-04, R-03).
//!
//! Why a flat golden and not a `stdin.json`→`expected-request.json` case dir:
//! the JS hook-client has NO `--provider`/`--model` flag — the OpenCode plugin
//! shells to the Rust binary, not the JS client (#5754). So `provider="opencode"`
//! and `model_id` are unreachable through the stdin→request build pipeline; the
//! arm functions (`canonicalize`/`normalize`/`is_opencode_event_alias`/
//! `is_valid_model_id`) are the honest parity surface. This mirrors the
//! `project-hash-goldens.json` precedent (a flat oracle golden consumed by a TS
//! test) exactly.
//!
//! Generated by `generate_parity_corpus` (via `scripts/regen-parity.sh`); never
//! in the default test pass. No production code is touched (C-07).

use std::fs;
use std::path::Path;

// The C2 Rust arm — the read-only oracle. `hook` is our grandparent module
// (hook -> parity_corpus_gen -> this); `opencode` is its `pub mod`, and
// `KNOWN_PROVIDERS` is a private const reachable from this descendant.
use super::super::KNOWN_PROVIDERS;
use super::super::opencode;

/// Events probed by the `normalize` goldens: the seven canonical names OpenCode
/// maps onto (identity today, AC-02b), PLUS raw OpenCode *source* bus names that
/// are NOT canonical — proving the arm returns the `__unknown__` sentinel rather
/// than silently coercing an unrecognized name (NFR-01). The C1 shim emits the
/// canonical names; the raw names are what OpenCode's own bus would carry.
const NORMALIZE_PROBE_EVENTS: &[&str] = &[
    // Seven canonical events (SessionStart..Stop) — the AC-02b parity axis.
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PostToolUse",
    "SubagentStart",
    "PreCompact",
    "Stop",
    // Raw OpenCode source names (see ARCHITECTURE.md event map): NOT canonical,
    // so both arms must return the sentinel — never a silent remap.
    "session.created",
    "chat.message",
    "tool.execute.before",
    "tool.execute.after",
    "session.idle",
    "experimental.session.compacting",
];

/// `model_id` carrier probes for `is_valid_model_id` parity (OQ-5, R-15, #5754).
///
/// Covers the present-model parity case (`ollama/qwen3-coder`), representative
/// `<providerID>/<modelID>` shapes, the charset rejects, and the trailing-newline
/// trap that JS `$`-without-`m` correctly rejects (#5754). The 129-char over-cap
/// probe and the empty ("absent"/None) probe are appended at build time.
const MODEL_ID_PROBES: &[&str] = &[
    "ollama/qwen3-coder",
    "anthropic/claude-sonnet-4-5",
    "github-copilot/gpt-4.1",
    "a",
    "model with space",
    "UPPER/case",
    "ollama/qwen3-coder\n",
    "emoji/🚀",
];

/// Regenerate `opencode-arm-goldens.json` from the `hook/opencode.rs` arm oracle.
///
/// Every value is COMPUTED by calling the shipped arm functions — none are
/// hand-written (#2984/#4751) — so a deliberate arm change is caught by the
/// zero-diff drift gate and a JS divergence by the consumer suite.
pub(crate) fn generate(out_dir: &Path) {
    // normalize: (canonical, provider) + the alias-guard verdict, per event.
    let normalize: Vec<serde_json::Value> = NORMALIZE_PROBE_EVENTS
        .iter()
        .map(|event| {
            let (canonical, provider) = opencode::normalize(event);
            serde_json::json!({
                "event_in": event,
                "canonical": canonical,
                "provider": provider,
                "is_opencode_event_alias": opencode::is_opencode_event_alias(event),
            })
        })
        .collect();

    // model_id_validation: value -> is_valid_model_id verdict. Append the
    // over-cap (MAX_LEN+1) and empty ("absent") boundary probes at build time.
    let over_cap = "a".repeat(unimatrix_engine::wire::MODEL_ID_MAX_LEN + 1);
    let mut model_probes: Vec<String> = MODEL_ID_PROBES.iter().map(|s| s.to_string()).collect();
    model_probes.push(over_cap);
    model_probes.push(String::new());
    let model_id_validation: Vec<serde_json::Value> = model_probes
        .iter()
        .map(|m| {
            serde_json::json!({
                "model_id": m,
                "valid": opencode::is_valid_model_id(m),
            })
        })
        .collect();

    let goldens = serde_json::json!({
        "generated_by": "parity_corpus_opencode.rs (hook/opencode.rs arm oracle, vnc-049 C8, col-022 split-brain guard)",
        "purpose": "Rust hook/opencode.rs (C2) <-> JS normalize.js (C3) arm parity: canonicalization, provider stamp, alias guard, and model_id carrier validation must match byte-for-byte. Editing one arm alone turns this golden (Rust) or the JS consumer suite red.",
        "provider": opencode::OPENCODE_PROVIDER,
        "unknown_event_sentinel": opencode::UNKNOWN_EVENT,
        "known_providers": KNOWN_PROVIDERS,
        "canonical_events": opencode::OPENCODE_CANONICAL_EVENTS,
        "normalize": normalize,
        "model_id_validation": model_id_validation,
    });

    let pretty = serde_json::to_string_pretty(&goldens).expect("opencode arm goldens serialize");
    fs::write(
        out_dir.join("opencode-arm-goldens.json"),
        format!("{pretty}\n"),
    )
    .unwrap_or_else(|e| panic!("write opencode-arm-goldens.json: {e}"));
}
