//! UDS-layer parity goldens (vnc-027, parity-corpus-uds component).
//!
//! Extends the vnc-026 corpus (ADR-001 oracle/golden/drift) with the UDS
//! transport layer that the TS `transport-uds.js` must match byte-for-byte:
//!
//!   * Framing goldens (AC-01, R-18): `write_frame(serialize_*(frame))` for the
//!     post-reduction request set and the sync-response set, INCLUDING the exact
//!     1,048,576-byte boundary in BOTH directions. `wire.rs` is the byte
//!     authority (`write_frame`/`serialize_request`/`serialize_response`); a
//!     future wire change breaks the TS drift compare loudly instead of silently
//!     splitting framing.
//!   * Hash goldens (AC-02, ADR-007 §3): `project.rs::compute_project_hash`
//!     regenerated through the corpus mechanism so a future Rust resolution/hash
//!     change is caught by the CI zero-diff gate (previously a static fixture).
//!
//! Generated by `generate_parity_corpus` (via `scripts/regen-parity.sh`); never
//! in the default test pass. No production code is touched.

use std::fs;
use std::path::Path;

use unimatrix_engine::project::compute_project_hash;
use unimatrix_engine::wire::{self, HookRequest, HookResponse, ImplantEvent, MAX_PAYLOAD_SIZE};

/// Frame a serialized payload exactly as the wire does (4-byte BE u32 length +
/// payload). Panics on the >1 MiB reject (callers stay within the cap).
fn frame_bytes(payload: &[u8]) -> Vec<u8> {
    let mut buf = Vec::with_capacity(4 + payload.len());
    wire::write_frame(&mut buf, payload).expect("payload within MAX_PAYLOAD_SIZE");
    buf
}

/// Write `<name>.payload.json` (the exact serialized wire bytes) and
/// `<name>.frame.bin` (the framed bytes) for one golden.
fn write_golden(dir: &Path, name: &str, payload: &[u8]) {
    fs::write(dir.join(format!("{name}.payload.json")), payload)
        .unwrap_or_else(|e| panic!("write {name}.payload.json: {e}"));
    fs::write(dir.join(format!("{name}.frame.bin")), frame_bytes(payload))
        .unwrap_or_else(|e| panic!("write {name}.frame.bin: {e}"));
}

fn write_request_golden(dir: &Path, name: &str, req: &HookRequest) -> String {
    let payload = wire::serialize_request(req).expect("request serializes");
    write_golden(dir, name, &payload);
    name.to_string()
}

fn write_response_golden(dir: &Path, name: &str, res: &HookResponse) -> String {
    let payload = wire::serialize_response(res).expect("response serializes");
    write_golden(dir, name, &payload);
    name.to_string()
}

/// A ContextSearch whose serialized form is EXACTLY `MAX_PAYLOAD_SIZE` bytes
/// (the write-direction 1 MiB boundary, R-18). Padding is plain ASCII so the
/// JSON length grows one byte per char (no escaping).
fn boundary_request() -> HookRequest {
    let base = HookRequest::ContextSearch {
        query: String::new(),
        session_id: None,
        role: None,
        task: None,
        feature: None,
        k: None,
        max_tokens: None,
        source: None,
        accept: None,
    };
    let base_len = wire::serialize_request(&base).expect("serializes").len();
    let pad = MAX_PAYLOAD_SIZE - base_len;
    let req = HookRequest::ContextSearch {
        query: "a".repeat(pad),
        session_id: None,
        role: None,
        task: None,
        feature: None,
        k: None,
        max_tokens: None,
        source: None,
        accept: None,
    };
    assert_eq!(
        wire::serialize_request(&req).expect("serializes").len(),
        MAX_PAYLOAD_SIZE,
        "boundary request must serialize to exactly 1 MiB"
    );
    req
}

/// A Text response whose serialized form is EXACTLY `MAX_PAYLOAD_SIZE` bytes
/// (the read-direction 1 MiB boundary, R-18).
fn boundary_response() -> HookResponse {
    let base_len = wire::serialize_response(&HookResponse::Text {
        body: String::new(),
    })
    .expect("serializes")
    .len();
    let pad = MAX_PAYLOAD_SIZE - base_len;
    let res = HookResponse::Text {
        body: "a".repeat(pad),
    };
    assert_eq!(
        wire::serialize_response(&res).expect("serializes").len(),
        MAX_PAYLOAD_SIZE,
        "boundary response must serialize to exactly 1 MiB"
    );
    res
}

/// Generate the `uds-framing/` golden family. Returns (request names, response
/// names) for the manifest.
fn generate_framing(out_dir: &Path) -> (Vec<String>, Vec<String>) {
    let dir = out_dir.join("uds-framing");
    fs::create_dir_all(&dir).unwrap_or_else(|e| panic!("create uds-framing dir: {e}"));

    // -- request frames (write direction, post-reduction set) --
    let mut requests = Vec::new();

    requests.push(write_request_golden(&dir, "req-ping", &HookRequest::Ping));

    requests.push(write_request_golden(
        &dir,
        "req-record-event",
        &HookRequest::RecordEvent {
            // Fixed timestamp keeps the golden byte-stable (no volatile field).
            event: ImplantEvent {
                event_type: "PostToolUse".to_string(),
                session_id: "sess-uds".to_string(),
                timestamp: 0,
                payload: serde_json::json!({ "tool_name": "Bash" }),
                topic_signal: Some("bash".to_string()),
                provider: Some("claude-code".to_string()),
                cycle_stamp: None,
            },
        },
    ));

    // Sync ContextSearch carries accept:"text/plain" on the wire (ADR-001 §2).
    requests.push(write_request_golden(
        &dir,
        "req-context-search-sync",
        &HookRequest::ContextSearch {
            query: "explain the auth flow".to_string(),
            session_id: Some("sess-uds".to_string()),
            role: Some("developer".to_string()),
            task: None,
            feature: None,
            k: None,
            max_tokens: None,
            source: Some("SubagentStart".to_string()),
            accept: Some("text/plain".to_string()),
        },
    ));

    // Queued / replayed ContextSearch never carries accept (skip_serializing_if).
    requests.push(write_request_golden(
        &dir,
        "req-context-search-fnf",
        &HookRequest::ContextSearch {
            query: "explain the auth flow".to_string(),
            session_id: Some("sess-uds".to_string()),
            role: None,
            task: None,
            feature: None,
            k: None,
            max_tokens: None,
            source: None,
            accept: None,
        },
    ));

    requests.push(write_request_golden(
        &dir,
        "req-compact-payload-sync",
        &HookRequest::CompactPayload {
            session_id: "sess-uds".to_string(),
            injected_entry_ids: vec![1, 2, 3],
            role: Some("developer".to_string()),
            feature: None,
            token_limit: Some(1000),
            transcript_excerpt: None,
            accept: Some("text/plain".to_string()),
        },
    ));

    requests.push(write_request_golden(
        &dir,
        "req-boundary-1mib",
        &boundary_request(),
    ));

    // -- response frames (read direction, sync-response set) --
    let mut responses = Vec::new();

    responses.push(write_response_golden(
        &dir,
        "res-text-entries",
        &HookResponse::Text {
            // Entries bodies carry the load-bearing injection header verbatim.
            body: "--- Unimatrix Context ---\n[1] prior decision\n".to_string(),
        },
    ));

    responses.push(write_response_golden(
        &dir,
        "res-text-briefing",
        &HookResponse::Text {
            body: "Use context_get with the entry ID for full content.".to_string(),
        },
    ));

    responses.push(write_response_golden(&dir, "res-ack", &HookResponse::Ack));

    responses.push(write_response_golden(
        &dir,
        "res-pong",
        &HookResponse::Pong {
            server_version: "0.7.2".to_string(),
        },
    ));

    responses.push(write_response_golden(
        &dir,
        "res-error-4xx",
        &HookResponse::Error {
            code: 400,
            message: "bad request".to_string(),
        },
    ));

    responses.push(write_response_golden(
        &dir,
        "res-error-5xx",
        &HookResponse::Error {
            code: 503,
            message: "unavailable".to_string(),
        },
    ));

    responses.push(write_response_golden(
        &dir,
        "res-boundary-1mib",
        &boundary_response(),
    ));

    let manifest = serde_json::json!({
        "generated_by": "parity_corpus_uds.rs (wire.rs write_frame/serialize_* oracle)",
        "frame_format": "4-byte big-endian u32 length prefix + payload bytes",
        "max_payload_size": MAX_PAYLOAD_SIZE,
        "requests": requests,
        "responses": responses,
    });
    let pretty = serde_json::to_string_pretty(&manifest).expect("manifest serializes");
    fs::write(dir.join("MANIFEST.json"), format!("{pretty}\n"))
        .unwrap_or_else(|e| panic!("write uds-framing MANIFEST: {e}"));

    (requests, responses)
}

/// Regenerate `project-hash-goldens.json` from the Rust hash oracle
/// (`compute_project_hash`), drift-checked like the rest of the corpus
/// (ADR-007 §3). `(input, normalized)` pairs are lexical (no OS resolution); the
/// committed hash is `compute_project_hash(normalized)` so the TS
/// `computeProjectHash` byte-matches it. The symlinked-path and worktree LAYOUT
/// parity is exercised TS-side in config.test.js against real fs fixtures.
fn generate_hash_goldens(out_dir: &Path) {
    // (input as the host might supply it, normalized path actually hashed).
    let pairs: &[(&str, &str)] = &[
        (
            "/tmp/unimatrix-parity/ascii-project",
            "/tmp/unimatrix-parity/ascii-project",
        ),
        (
            "/tmp/unimatrix-parity/プロジェクト-ümlaut",
            "/tmp/unimatrix-parity/プロジェクト-ümlaut",
        ),
        (
            "/tmp/unimatrix-parity/trailing/",
            "/tmp/unimatrix-parity/trailing",
        ),
        ("/workspaces/unimatrix", "/workspaces/unimatrix"),
        (
            "C:\\Program Files\\My Project",
            "C:\\Program Files\\My Project",
        ),
    ];

    let cases: Vec<serde_json::Value> = pairs
        .iter()
        .map(|(input, normalized)| {
            serde_json::json!({
                "input": input,
                "normalized": normalized,
                "hash": compute_project_hash(Path::new(normalized)),
            })
        })
        .collect();

    let goldens = serde_json::json!({
        "generated_by": "parity_corpus_uds.rs::generate_hash_goldens (project.rs::compute_project_hash oracle, vnc-027 ADR-007 §3)",
        "algorithm": "first 16 hex chars of SHA-256 over the UTF-8 bytes of the normalized root path string",
        "cases": cases,
    });
    let pretty = serde_json::to_string_pretty(&goldens).expect("goldens serialize");
    fs::write(
        out_dir.join("project-hash-goldens.json"),
        format!("{pretty}\n"),
    )
    .unwrap_or_else(|e| panic!("write project-hash-goldens.json: {e}"));
}

/// Emit the full UDS parity layer into the committed corpus dir.
pub(crate) fn generate(out_dir: &Path) {
    let (requests, responses) = generate_framing(out_dir);
    assert!(
        !requests.is_empty() && !responses.is_empty(),
        "UDS framing corpus must be non-empty (vacuous-pass guard)"
    );
    generate_hash_goldens(out_dir);
}
